# https://tombi-toml.github.io/tombi/configuration.html

[format.rules]
  indent-style = "space"
  indent-sub-tables = true
  indent-table-key-value-pairs = true
  indent-width = 2
  line-width = 120
  string-quote-style = "double"
  trailing-comment-alignment = true
