"""Golden digest parity: the Python canon agrees with the TypeScript sources.

The committed fixtures under ``tests/golden/`` are generated by the declared
TypeScript task (``task reviewmatic-py:fixtures``, byte-checked in
``generate:check``). Each fixture records a shared input, its canonical JSON
digest, and the TypeScript validation verdict. This module recomputes both
with the materialized canonical runtime; a single divergent digest or verdict
fails here, which keeps the two ports honest without a live TS run.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from reviewmatic.portable import state_artifacts
from reviewmatic.portable.portable_gitlab import contract, review_semver
from reviewmatic.portable.portable_gitlab.label_assessment import validate_label_assessments

GOLDEN = Path(__file__).resolve().parent / "golden"


def fixtures() -> list[dict[str, Any]]:
    return [json.loads(path.read_text(encoding="utf-8")) for path in sorted(GOLDEN.glob("*.json"))]


def test_golden_fixtures_exist() -> None:
    names = {path.name for path in GOLDEN.glob("*.json")}
    kinds = {fixture["kind"] for fixture in fixtures()}
    assert len(names) >= 17
    assert {
        "canonical_digest",
        "artifact_validation_v2",
        "semver_evidence",
        "semver_assessment",
        "label_intent",
    } <= kinds


def test_golden_fixtures_carry_complete_expectations() -> None:
    for fixture in fixtures():
        assert set(fixture) == {"name", "kind", "input", "expected"}, fixture["name"]
        expected = fixture["expected"]
        assert {"digest", "valid", "python_valid"} <= set(expected), fixture["name"]
        assert contract.is_digest(expected["digest"]), fixture["name"]
        assert isinstance(expected["valid"], bool), fixture["name"]
        assert isinstance(expected["python_valid"], bool), fixture["name"]
        if expected["valid"] is not expected["python_valid"]:
            reason = expected.get("divergence_reason")
            assert isinstance(reason, str) and reason, fixture["name"]
        else:
            assert "divergence_reason" not in expected, fixture["name"]


@pytest.mark.parametrize("fixture", fixtures(), ids=lambda fixture: fixture.get("name", "?"))
def test_python_canon_matches_the_golden_digest_and_verdict(fixture: dict[str, Any]) -> None:
    assert contract.digest(fixture["input"]) == fixture["expected"]["digest"]
    # Both canonical serializers must produce identical bytes (the state
    # artifact form carries no trailing newline; the contract digest does).
    assert state_artifacts.canonical_json(fixture["input"]) + b"\n" == contract.canonical(
        fixture["input"]
    )
    # The Python canon is the strictness reference (decision 33): its own
    # verdict must match the declared python_valid expectation, and the
    # TypeScript divergence stays an explicitly documented exception.
    assert verdict(fixture) is fixture["expected"]["python_valid"]


def verdict(fixture: dict[str, Any]) -> bool:
    kind, value = fixture["kind"], fixture["input"]
    if kind == "canonical_digest":
        return True
    if kind == "artifact_validation_v2":
        try:
            contract.validate_v2_artifact(value["artifact"], value["kind"])
        except contract.WorkflowError:
            return False
        return True
    if kind == "semver_evidence":
        return review_semver.evidence_is_valid(value)
    if kind == "semver_assessment":
        return review_semver.assessment_is_valid(value)
    if kind == "label_intent":
        return bool(contract.label_intent_is_valid(value))
    raise AssertionError(f"unknown fixture kind: {kind}")


def test_label_assessment_contract_stays_importable() -> None:
    evidence = {
        "labels": {
            "items": [{"name": "bug", "description": None}],
            "complete": True,
            "errors": [],
            "pages": 0,
            "truncated": False,
        },
        "object": {"labels": ["bug"]},
    }
    assessments = [
        {"name": "bug", "status": "applicable", "rationale": "The change fixes a defect."}
    ]
    result = validate_label_assessments(evidence, assessments, "patch")
    assert result["assessments"][0]["name"] == "bug"
    assert result["current"] == ["bug"]
    assert result["add"] == []
