import { requirePackageVersion } from "./package-metadata.js";

export const CATALOG = {
  skills: [
    "agents-md",
    "askme",
    "ast-grep",
    "code-explain",
    "code-review",
    "commit-msg",
    "docs-prepare",
    "docs-review",
    "goal",
    "humanize",
    "mattermost",
    "mattermost-triage",
    "mr-prepare",
    "release-prepare",
    "release-review",
    "rtk",
    "skill-doctor",
    "slides-prompts-prepare",
    "spec-manage",
    "stopit",
    "briefing",
    "task-prepare",
    "task-review",
    "task-triage",
    "taskmatic",
    "team-1on1",
    "team-agreements",
    "team-feedback",
    "team-health",
    "team-incident",
    "team-onboarding",
    "team-people",
    "team-performance",
    "team-report",
    "team-retro",
    "team-roadmap",
    "team-sprint-close",
    "team-sprint-start",
  ],
  plugins: ["rules-injector", "rtk", "zed-bell"],
  agents: ["manager", "architect", "mapper", "worker", "review", "critic"],
  package_commands: ["rtk-stats"],
  tools: ["route"],
  version: requirePackageVersion(),
} as const;
