// Syncs portable skill metadata and declared relations from the repository
// into typed site data. The generated files are build inputs and stay out of
// Git; every validation failure exits non-zero so the build gate stops.
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const siteRoot = fileURLToPath(new URL("..", import.meta.url));
const repoRoot = path.resolve(siteRoot, "..", "..");
const skillsDir = path.join(repoRoot, "skills");
const relationsPath = path.join(repoRoot, "shared", "skill-relations.json");
const ruCatalogPath = path.join(repoRoot, "docs", "ru", "reference", "skill-catalog.md");
const generatedDir = path.join(siteRoot, "src", "generated");

const RELATION_TYPES = new Set(["requires", "uses", "recommends"]);
const RU_CATALOG_SECTION = "## Активные навыки";
const RU_CATALOG_ROW = /^\| `([^`]+)` \|(.*?)\|$/;

/**
 * Extracts the `slug -> Russian description` mapping from the active-skills
 * table of `docs/ru/reference/skill-catalog.md`. Any structural deviation is
 * an explicit error so drift between the catalog and the table stops the gate.
 */
export function parseRuSkillDescriptions(markdown) {
  const sectionStart = markdown.indexOf(`${RU_CATALOG_SECTION}\n`);
  if (sectionStart === -1) {
    throw new Error(`RU skill catalog has no ${RU_CATALOG_SECTION} section`);
  }
  const rest = markdown.slice(sectionStart + RU_CATALOG_SECTION.length + 1);
  const section = rest.split(/\n## /, 1)[0];
  const descriptions = new Map();
  for (const line of section.split("\n")) {
    const match = RU_CATALOG_ROW.exec(line.trim());
    if (match === null) {
      continue;
    }
    const slug = match[1];
    const description = match[2].trim();
    if (descriptions.has(slug)) {
      throw new Error(`duplicate RU skill catalog row: ${slug}`);
    }
    if (description === "") {
      throw new Error(`empty RU description in the skill catalog: ${slug}`);
    }
    descriptions.set(slug, description);
  }
  if (descriptions.size === 0) {
    throw new Error("RU skill catalog table has no rows");
  }
  return descriptions;
}

/**
 * Reads `skills/<name>/SKILL.source.md` frontmatter for every portable skill,
 * pairs each entry with its Russian description from the RU skill catalog, and
 * validates the declared relation graph endpoints against the catalog.
 */
export async function collectCatalog() {
  const entries = (await readdir(skillsDir, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name));
  const skills = [];
  for (const entry of entries) {
    const source = path.join(skillsDir, entry.name, "SKILL.source.md");
    const raw = await readFile(source, "utf8");
    const match = /^---\r?\n(.*?)\r?\n---(?:\r?\n|$)/s.exec(raw);
    if (match === null) {
      throw new Error(`missing frontmatter: ${source}`);
    }
    const meta = parse(match[1]);
    if (meta === null || typeof meta !== "object" || meta.name !== entry.name) {
      throw new Error(`frontmatter name does not match the directory: ${source}`);
    }
    if (typeof meta.description !== "string" || meta.description.trim() === "") {
      throw new Error(`frontmatter description is empty: ${source}`);
    }
    skills.push({ name: meta.name, description: meta.description.trim() });
  }
  const names = new Set(skills.map((skill) => skill.name));
  const ruDescriptions = parseRuSkillDescriptions(await readFile(ruCatalogPath, "utf8"));
  for (const skill of skills) {
    const ru = ruDescriptions.get(skill.name);
    if (ru === undefined) {
      throw new Error(`skill has no row in the RU skill catalog table: ${skill.name}`);
    }
    skill.descriptionRu = ru;
  }
  for (const slug of ruDescriptions.keys()) {
    if (!names.has(slug)) {
      throw new Error(`RU skill catalog row names an unknown skill: ${slug}`);
    }
  }
  const declared = JSON.parse(await readFile(relationsPath, "utf8"));
  const relations = [];
  for (const relation of declared.relations ?? []) {
    if (!names.has(relation.from) || !names.has(relation.to)) {
      throw new Error(`relation references an unknown skill: ${JSON.stringify(relation)}`);
    }
    if (!RELATION_TYPES.has(relation.type)) {
      throw new Error(`relation has an undeclared type: ${JSON.stringify(relation)}`);
    }
    relations.push({
      from: relation.from,
      to: relation.to,
      type: relation.type,
      reason: typeof relation.reason === "string" ? relation.reason : "",
    });
  }
  return { skills, relations };
}

async function writeCatalog() {
  const catalog = await collectCatalog();
  const header = "// Generated by scripts/sync-content.mjs; do not edit.\n";
  const body = `export interface SkillEntry {\n  name: string;\n  description: string;\n  descriptionRu: string;\n}\n\nexport interface RelationEntry {\n  from: string;\n  to: string;\n  type: "requires" | "uses" | "recommends";\n  reason: string;\n}\n\nexport interface Catalog {\n  skills: SkillEntry[];\n  relations: RelationEntry[];\n}\n\nexport const catalog: Catalog = ${JSON.stringify(catalog, null, 2)};\n`;
  await mkdir(generatedDir, { recursive: true });
  await writeFile(path.join(generatedDir, "skills.ts"), header + body);
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await writeCatalog();
}
