export const CATALOG = {
  skills: [
    "agents-md",
    "askme",
    "ast-grep",
    "code-explain",
    "code-review",
    "commit-msg",
    "docs-prepare",
    "docs-review",
    "doit",
    "goal",
    "humanize",
    "lsp-report",
    "mattermost",
    "mr-prepare",
    "release-prepare",
    "release-review",
    "rtk",
    "skill-improve",
    "slides-prompts-prepare",
    "spec-manage",
    "stopit",
    "summary",
    "task-prepare",
    "task-review",
    "task-triage",
    "team-retro",
    "team-roadmap",
    "team-sprint-close",
    "team-sprint-start",
  ],
  plugins: [
    "background-attempts",
    "schedule",
    "autonomy-policy",
    "rules-injector",
    "rtk",
    "zed-bell",
    "zed-clickable-paths",
  ],
  replacements: ["capabilities", "doctor", "reconcile", "agent_profiles"],
  version: "2.0.0",
} as const;
